[package]
name = "losig-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bounded-integer.workspace = true
serde.workspace = true

[lints]
workspace = true
